gx.num.dec={bigDecimal:function(m,q,v){this.div=function(b,a){return(b-b%a)/a};this.arraycopy=function(b,a,c,d,e){var g;if(d>a)for(g=e-1;0<=g;--g)c[g+d]=b[g+a];else for(g=0;g<e;++g)c[g+d]=b[g+a]};this.createArrayWithZeros=function(b){var a=Array(b),c;for(c=0;c<b;++c)a[c]=0;return a};this.abs=function(b){"undefined"==typeof b&&(b=this.plainMC);return this.ind==this.isneg?this.negate(b):this.plus(b)};this.add=function(b,a){"undefined"==typeof a&&(a=this.plainMC);a.lostDigits&&this.checkdigits(b,a.digits);
var c=this;if(0==c.ind&&a.form!=gx.num.dec.PLAIN)return b.plus(a);if(0==b.ind&&a.form!=gx.num.dec.PLAIN)return c.plus(a);var d=a.digits;0<d&&(c.mant.length>d&&(c=this.clone(c).round(a)),b.mant.length>d&&(b=this.clone(b).round(a)));var e=new gx.num.dec.bigDecimal;var g=c.mant;var f=c.mant.length;var h=b.mant;var l=b.mant.length;if(c.exp==b.exp)e.exp=c.exp;else if(c.exp>b.exp){var k=f+c.exp-b.exp;if(k>=l+d+1&&0<d)return e.mant=g,e.exp=c.exp,e.ind=c.ind,f<d&&(e.mant=this.extend(c.mant,d),e.exp-=d-f),
e.finish(a,!1);e.exp=b.exp;k>d+1&&0<d&&(k=k-d-1,l-=k,e.exp+=k,k=d+1);k>f&&(f=k)}else{k=l+b.exp-c.exp;if(k>=f+d+1&&0<d)return e.mant=h,e.exp=b.exp,e.ind=b.ind,l<d&&(e.mant=this.extend(b.mant,d),e.exp-=d-l),e.finish(a,!1);e.exp=c.exp;k>d+1&&0<d&&(k=k-d-1,f-=k,e.exp+=k,k=d+1);k>l&&(l=k)}e.ind=c.ind==this.iszero?this.ispos:c.ind;if((c.ind==this.isneg?1:0)==(b.ind==this.isneg?1:0))d=1;else if(d=-1,b.ind!=this.iszero)if(f<l||c.ind==this.iszero)k=g,g=h,h=k,k=f,f=l,l=k,e.ind=-e.ind;else if(!(f>l)){var u=
k=0;var r=g.length-1;var z=h.length-1;c:for(;;){if(k<=r)var B=g[k];else{if(u>z){if(a.form!=gx.num.dec.PLAIN)return new gx.num.dec.bigDecimal("0");break c}B=0}var D=u<=z?h[u]:0;if(B!=D){B<D&&(k=g,g=h,h=k,k=f,f=l,l=k,e.ind=-e.ind);break c}k++;u++}}e.mant=this.byteaddsub(g,f,h,l,d,!1);return e.finish(a,!1)};this.compareTo=function(b,a){"undefined"==typeof a&&(a=this.plainMC);a.lostDigits&&this.checkdigits(b,a.digits);if(this.ind==b.ind&&this.exp==b.exp){var c=this.mant.length;if(c<b.mant.length)return-this.ind;
if(c>b.mant.length)return this.ind;if(c<=a.digits||0==a.digits){a=0;for(;0<c;c--,a++){if(this.mant[a]<b.mant[a])return-this.ind;if(this.mant[a]>b.mant[a])return this.ind}return 0}}else{if(this.ind<b.ind)return-1;if(this.ind>b.ind)return 1}b=this.clone(b);b.ind=-b.ind;return this.add(b,a).ind};this.divide=function(b,a,c){var d=-1;if("undefined"!=typeof a)"number"==typeof a&&(a=new gx.num.dec.mthctx(0,gx.num.dec.PLAIN,!1,a));else if("undefined"!=typeof c){d=a;if(0>d)throw"divide(): Negative scale: "+
d;a=new gx.num.dec.mthctx(0,gx.num.dec.PLAIN,!1,c)}else"undefined"==typeof a&&(a=this.plainMC);return this.dodivide("D",b,a,d)};this.divideInteger=function(b,a){"undefined"==typeof a&&(a=this.plainMC);return this.dodivide("I",b,a,0)};this.max=function(b,a){"undefined"==typeof a&&(a=this.plainMC);return 0<=this.compareTo(b,a)?this.plus(a):b.plus(a)};this.min=function(b,a){"undefined"==typeof a&&(a=this.plainMC);return 0>=this.compareTo(b,a)?this.plus(a):b.plus(a)};this.multiply=function(b,a){"undefined"==
typeof a&&(a=this.plainMC);a.lostDigits&&this.checkdigits(b,a.digits);var c=this;var d=0;var e=a.digits;0<e?(c.mant.length>e&&(c=this.clone(c).round(a)),b.mant.length>e&&(b=this.clone(b).round(a))):(0<c.exp&&(d+=c.exp),0<b.exp&&(d+=b.exp));if(c.mant.length<b.mant.length){e=c.mant;var g=b.mant}else e=b.mant,g=c.mant;var f=e.length+g.length-1;var h=9<e[0]*g[0]?f+1:f;var l=new gx.num.dec.bigDecimal;h=this.createArrayWithZeros(h);var k=e.length;var u=0;for(;0<k;k--,u++){var r=e[u];0!=r&&(h=this.byteaddsub(h,
h.length,g,f,r,!0));f--}l.ind=c.ind*b.ind;l.exp=c.exp+b.exp-d;l.mant=0==d?h:this.extend(h,h.length+d);return l.finish(a,!1)};this.negate=function(b){"undefined"==typeof b&&(b=this.plainMC);b.lostDigits&&this.checkdigits(null,b.digits);var a=this.clone(this);a.ind=-a.ind;return a.finish(b,!1)};this.plus=function(b){"undefined"==typeof b&&(b=this.plainMC);b.lostDigits&&this.checkdigits(null,b.digits);return b.form==gx.num.dec.PLAIN&&this.form==gx.num.dec.PLAIN&&(this.mant.length<=b.digits||0==b.digits)?
this:this.clone(this).finish(b,!1)};this.pow=function(b,a){"undefined"==typeof a&&(a=this.plainMC);a.lostDigits&&this.checkdigits(b,a.digits);var c=b.intcheck(this.MinArg,this.MaxArg);var d=this;var e=a.digits;if(0==e){if(b.ind==this.isneg)throw"pow(): Negative power: "+b.toString();e=0}else{if(b.mant.length+b.exp>e)throw"pow(): Too many digits: "+b.toString();d.mant.length>e&&(d=this.clone(d).round(a));var g=b.mant.length+b.exp;e=e+g+1}e=new gx.num.dec.mthctx(e,a.form,!1,a.roundingMode);g=new gx.num.dec.bigDecimal("1");
if(0==c)return g;0>c&&(c=-c);var f=!1;var h=1;a:for(;;h++){c+=c;0>c&&(f=!0,g=g.multiply(d,e));if(31==h)break a;if(!f)continue a;g=g.multiply(g,e)}0>b.ind&&(g=(new gx.num.dec.bigDecimal("1")).divide(g,e));return g.finish(a,!0)};this.remainder=function(b,a){"undefined"==typeof a&&(a=this.plainMC);return this.dodivide("R",b,a,-1)};this.substract=function(b,a){"undefined"==typeof a&&(a=this.plainMC);a.lostDigits&&this.checkdigits(b,a.digits);b=this.clone(b);b.ind=-b.ind;return this.add(b,a)};this.equals=
function(b){if(null==b||!(b instanceof gx.num.dec.bigDecimal)||this.ind!=b.ind)return!1;if(this.mant.length==b.mant.length&&this.exp==b.exp&&this.form==b.form){var a=this.mant.length;var c=0;for(;0<a;a--,c++)if(this.mant[c]!=b.mant[c])return!1}else{a=this.layout();b=b.layout();if(a.length!=b.length)return!1;var d=a.length;c=0;for(;0<d;d--,c++)if(a[c]!=b[c])return!1}return!0};this.format=function(b,a,c,d,e,g){"undefined"==typeof c&&(d=c=-1,e=gx.num.dec.SCIENTIFIC,g=gx.num.dec.ROUND_HALF_UP);(-1>b||
0==b)&&this.badarg("format",1,b);-1>a&&this.badarg("format",2,a);(-1>c||0==c)&&this.badarg("format",3,c);-1>d&&this.badarg("format",4,d);e!=gx.num.dec.SCIENTIFIC&&e!=gx.num.dec.ENGINEERING&&(-1==e?e=gx.num.dec.SCIENTIFIC:this.badarg("format",5,e));if(g!=gx.num.dec.ROUND_HALF_UP)try{-1==g?g=gx.num.dec.ROUND_HALF_UP:new gx.num.dec.mthctx(9,gx.num.dec.SCIENTIFIC,!1,g)}catch(l){this.badarg("format",6,g)}var f=this.clone(this);if(-1==d)f.form=gx.num.dec.PLAIN;else if(f.ind==this.iszero)f.form=gx.num.dec.PLAIN;
else{var h=f.exp+f.mant.length;f.form=h>d?e:-5>h?e:gx.num.dec.PLAIN}if(0<=a)a:for(;;){f.form==gx.num.dec.PLAIN?d=-f.exp:f.form==gx.num.dec.SCIENTIFIC?d=f.mant.length-1:(d=(f.exp+f.mant.length-1)%3,0>d&&(d=3+d),d++,d=d>=f.mant.length?0:f.mant.length-d);if(d==a)break a;if(d<a){g=this.extend(f.mant,f.mant.length+a-d);f.mant=g;f.exp-=a-d;if(f.exp<this.MinExp)throw"format(): Exponent Overflow: "+f.exp;break a}d-=a;if(d>f.mant.length){f.mant=(new gx.num.dec.bigDecimal("0")).mant;f.ind=this.iszero;f.exp=
0;continue a}e=f.mant.length-d;h=f.exp;f.round(e,g);if(f.exp-h==d)break a}a=f.layout();if(0<b){g=a.length;f=0;a:for(;0<g;g--,f++){if("."==a[f])break a;if("E"==a[f])break a}f>b&&this.badarg("format",1,b);if(f<b){g=Array(a.length+b-f);f=b-f;b=0;for(;0<f;f--,b++)g[b]=" ";this.arraycopy(a,0,g,b,a.length);a=g}}if(0<c){b=a.length-1;f=a.length-1;a:for(;0<b;b--,f--)if("E"==a[f])break a;if(0==f){g=Array(a.length+c+2);this.arraycopy(a,0,g,0,a.length);c+=2;b=a.length;for(;0<c;c--,b++)g[b]=" ";a=g}else if(d=
a.length-f-2,d>c&&this.badarg("format",3,c),d<c){g=Array(a.length+c-d);this.arraycopy(a,0,g,0,f+2);c-=d;b=f+2;for(;0<c;c--,b++)g[b]="0";this.arraycopy(a,f+2,g,b,d);a=g}}return a.join("")};this.intValueExact=function(){if(this.ind==this.iszero)return 0;var b=this.mant.length-1;if(0>this.exp){b+=this.exp;if(!this.allzero(this.mant,b+1))throw"intValueExact(): Decimal part non-zero: "+this.toString();if(0>b)return 0;var a=0}else{if(9<this.exp+b)throw"intValueExact(): Conversion overflow: "+this.toString();
a=this.exp}var c=0;var d=b+a;var e=0;for(;e<=d;e++)c*=10,e<=b&&(c+=this.mant[e]);if(9==b+a&&(b=div(c,1E9),b!=this.mant[0])){if(-2147483648==c&&this.ind==this.isneg&&2==this.mant[0])return c;throw"intValueExact(): Conversion overflow: "+this.toString();}return this.ind==this.ispos?c:-c};this.movePointLeft=function(b){var a=this.clone(this);a.exp-=b;return a.finish(this.plainMC,!1)};this.movePointRight=function(b){var a=this.clone(this);a.exp+=b;return a.finish(this.plainMC,!1)};this.scale=function(){return 0<=
this.exp?0:-this.exp};this.setScale=function(b,a){"undefined"==typeof a&&(a=gx.num.dec.ROUND_UNNECESSARY);var c=this.scale();if(c==b&&this.form==gx.num.dec.PLAIN)return this;var d=this.clone(this);if(c<=b)a=0==c?d.exp+b:b-c,d.mant=this.extend(d.mant,d.mant.length+a),d.exp=-b;else{if(0>b)throw"setScale(): Negative scale: "+b;c=d.mant.length-(c-b);d=d.round(c,a);d.exp!=-b&&(d.mant=this.extend(d.mant,d.mant.length+1),--d.exp)}d.form=gx.num.dec.PLAIN;return d};this.signum=function(){return this.ind};
this.toString=function(){return this.layout().join("")};this.toFixed=function(b){return this.setScale(b,gx.num.dec.ROUND_UP).toString()};this.layout=function(){var b=Array(this.mant.length);var a=this.mant.length;var c=0;for(;0<a;a--,c++)b[c]=this.mant[c]+"";if(this.form!=gx.num.dec.PLAIN){c="";this.ind==this.isneg&&(c+="-");a=this.exp+b.length-1;if(this.form==gx.num.dec.SCIENTIFIC)c+=b[0],1<b.length&&(c+="."),c+=b.slice(1).join("");else{var d=a%3;0>d&&(d=3+d);a-=d;d++;if(d>=b.length)for(c+=b.join(""),
d-=b.length;0<d;d--)c+="0";else c+=b.slice(0,d).join(""),c+=".",c+=b.slice(d).join("")}0!=a&&(0>a?(b="-",a=-a):b="+",c=c+"E"+b+a);return c.split("")}if(0==this.exp){if(0<=this.ind)return b;d=Array(b.length+1);d[0]="-";this.arraycopy(b,0,d,1,b.length);return d}a=this.ind==this.isneg?1:0;var e=this.exp+b.length;if(1>e){c=a+2-this.exp;d=Array(c);0!=a&&(d[0]="-");d[a]="0";d[a+1]=".";var g=-e;c=a+2;for(;0<g;g--,c++)d[c]="0";this.arraycopy(b,0,d,a+2-e,b.length);return d}if(e>b.length){d=Array(a+e);0!=a&&
(d[0]="-");this.arraycopy(b,0,d,a,b.length);e-=b.length;c=a+b.length;for(;0<e;e--,c++)d[c]="0";return d}c=a+1+b.length;d=Array(c);0!=a&&(d[0]="-");this.arraycopy(b,0,d,a,e);d[a+e]=".";this.arraycopy(b,e,d,a+e+1,b.length-e);return d};this.intcheck=function(b,a){var c=this.intValueExact();if(c<b||c>a)throw"intcheck(): Conversion overflow: "+c;return c};this.dodivide=function(b,a,c,d){c.lostDigits&&this.checkdigits(a,c.digits);var e=this;if(0==a.ind)throw"dodivide(): Divide by 0";if(0==e.ind)return c.form!=
gx.num.dec.PLAIN?new gx.num.dec.bigDecimal("0"):-1==d?e:e.setScale(d);var g=c.digits;0<g?(e.mant.length>g&&(e=this.clone(e).round(c)),a.mant.length>g&&(a=this.clone(a).round(c))):(-1==d&&(d=e.scale()),g=e.mant.length,d!=-e.exp&&(g=g+d+e.exp),g=g-(a.mant.length-1)-a.exp,g<e.mant.length&&(g=e.mant.length),g<a.mant.length&&(g=a.mant.length));var f=e.exp-a.exp+e.mant.length-a.mant.length;if(0>f&&"D"!=b)return"I"==b?new gx.num.dec.bigDecimal("0"):this.clone(e).finish(c,!1);var h=new gx.num.dec.bigDecimal;
h.ind=e.ind*a.ind;h.exp=f;h.mant=this.createArrayWithZeros(g+1);var l=g+g+1;f=this.extend(e.mant,l);var k=l;var u=a.mant;var r=l;var z=10*u[0]+1;1<u.length&&(z+=u[1]);l=0;a:for(;;){var B=0;b:for(;;){if(k<r)break b;if(k==r){c:{var D=k;var t=0;for(;0<D;D--,t++){var E=t<u.length?u[t]:0;if(f[t]<E)break b;if(f[t]>E)break c}B++;h.mant[l]=B;l++;f[0]=0;break a}t=f[0]}else t=10*f[0],1<k&&(t+=f[1]);t=div(10*t,z);0==t&&(t=1);B+=t;f=this.byteaddsub(f,k,u,r,-t,!0);if(0!=f[0])continue b;E=k-2;t=0;c:for(;t<=E;t++){if(0!=
f[t])break c;k--}if(0==t)continue b;this.arraycopy(f,t,f,0,k)}if(0!=l||0!=B){h.mant[l]=B;l++;if(l==g+1)break a;if(0==f[0])break a}if(0<=d&&-h.exp>d)break a;if("D"!=b&&0>=h.exp)break a;--h.exp;r--}0==l&&(l=1);if("I"==b||"R"==b){if(l+h.exp>g)throw"dodivide(): Integer overflow";if("R"==b){if(0==h.mant[0])return this.clone(e).finish(c,!1);if(0==f[0])return new gx.num.dec.bigDecimal("0");h.ind=e.ind;d=g+g+1-e.mant.length;h.exp=h.exp-d+e.exp;d=k;t=d-1;b:for(;1<=t&&h.exp<e.exp&&h.exp<a.exp;t--){if(0!=f[t])break b;
d--;h.exp+=1}d<f.length&&(a=Array(d),this.arraycopy(f,0,a,0,d),f=a);h.mant=f;return h.finish(c,!1)}}else 0!=f[0]&&(a=h.mant[l-1],0==a%5&&(h.mant[l-1]=a+1));if(0<=d)return l!=h.mant.length&&(h.exp-=h.mant.length-l),a=h.mant.length-(-h.exp-d),h.round(a,c.roundingMode),h.exp!=-d&&(h.mant=this.extend(h.mant,h.mant.length+1),--h.exp),h.finish(c,!0);if(l==h.mant.length)h.round(c);else{if(0==h.mant[0])return new gx.num.dec.bigDecimal("0");a=Array(l);this.arraycopy(h.mant,0,a,0,l);h.mant=a}return h.finish(c,
!0)};this.bad=function(b,a){throw b+"Not a number: "+a;};this.badarg=function(b,a,c){throw"Bad argument "+a+" to "+b+": "+c;};this.extend=function(b,a){if(b.length==a)return b;a=createArrayWithZeros(a);this.arraycopy(b,0,a,0,b.length);return a};this.byteaddsub=function(b,a,c,d,e,g){var f;var h=b.length;var l=c.length;--a;var k=f=d-1;k<a&&(k=a);d=null;g&&k+1==h&&(d=b);null==d&&(d=this.createArrayWithZeros(k+1));var u=!1;1==e?u=!0:-1==e&&(u=!0);var r=0;var z=k;a:for(;0<=z;z--){0<=a&&(a<h&&(r+=b[a]),
a--);0<=f&&(f<l&&(r=u?0<e?r+c[f]:r-c[f]:r+c[f]*e),f--);if(10>r&&0<=r){d[z]=r;r=0;continue a}r+=90;d[z]=this.diginit()[r];r=this.bytecar[r]}if(0==r)return d;c=null;g&&k+2==b.length&&(c=b);null==c&&(c=Array(k+2));c[0]=r;g=k+1;b=0;for(;0<g;g--,b++)c[b+1]=d[b];return c};this.diginit=function(){var b=Array(190);var a=0;a:for(;189>=a;a++){var c=a-90;if(0<=c){b[a]=c%10;this.bytecar[a]=this.div(c,10);continue a}c+=100;b[a]=c%10;this.bytecar[a]=this.div(c,10)-10}return b};this.clone=function(b){var a=new gx.num.dec.bigDecimal;
a.ind=b.ind;a.exp=b.exp;a.form=b.form;a.mant=b.mant;return a};this.checkdigits=function(b,a){if(0!=a){if(this.mant.length>a&&!this.allzero(this.mant,a))throw"Too many digits: "+this.toString();if(null!=b&&b.mant.length>a&&!this.allzero(b.mant,a))throw"Too many digits: "+b.toString();}};this.round=function(b,a){"undefined"==typeof a&&(a=b,b=a.digits,a=a.roundingMode);var c=this.mant.length-b;if(0>=c)return this;this.exp+=c;var d=this.ind;var e=this.mant;if(0<b){this.mant=Array(b);this.arraycopy(e,
0,this.mant,0,b);c=!0;var g=e[b]}else this.mant=(new gx.num.dec.bigDecimal("0")).mant,this.ind=this.iszero,c=!1,g=0==b?e[0]:0;var f=0;if(a==gx.num.dec.ROUND_HALF_UP)5<=g&&(f=d);else if(a==gx.num.dec.ROUND_UNNECESSARY){if(!this.allzero(e,b))throw"round(): Rounding necessary";}else if(a==gx.num.dec.ROUND_HALF_DOWN)5<g?f=d:5==g&&(this.allzero(e,b+1)||(f=d));else if(a==gx.num.dec.ROUND_HALF_EVEN)5<g?f=d:5==g&&(this.allzero(e,b+1)?1==this.mant[this.mant.length-1]%2&&(f=d):f=d);else if(a!=gx.num.dec.ROUND_DOWN)if(a==
gx.num.dec.ROUND_UP)this.allzero(e,b)||(f=d);else if(a==gx.num.dec.ROUND_CEILING)0<d&&(this.allzero(e,b)||(f=d));else if(a==gx.num.dec.ROUND_FLOOR)0>d&&(this.allzero(e,b)||(f=d));else throw"round(): Bad round value: "+a;0!=f&&(this.ind==this.iszero?(this.mant=(new gx.num.dec.bigDecimal("1")).mant,this.ind=f):(this.ind==this.isneg&&(f=-f),b=this.byteaddsub(this.mant,this.mant.length,(new gx.num.dec.bigDecimal("1")).mant,1,f,c),b.length>this.mant.length?(this.exp++,this.arraycopy(b,0,this.mant,0,this.mant.length)):
this.mant=b));if(this.exp>this.MaxExp)throw"round(): Exponent Overflow: "+this.exp;return this};this.allzero=function(b,a){0>a&&(a=0);var c=b.length-1;for(;a<=c;a++)if(0!=b[a])return!1;return!0};this.finish=function(b,a){0!=b.digits&&this.mant.length>b.digits&&this.round(b);if(a&&b.form!=gx.num.dec.PLAIN){var c=this.mant.length;a=c-1;a:for(;1<=a;a--){if(0!=this.mant[a])break a;c--;this.exp++}if(c<this.mant.length){var d=Array(c);this.arraycopy(this.mant,0,d,0,c);this.mant=d}}this.form=gx.num.dec.PLAIN;
c=this.mant.length;a=0;for(;0<c;c--,a++)if(0!=this.mant[a]){0<a&&(d=Array(this.mant.length-a),this.arraycopy(this.mant,a,d,0,this.mant.length-a),this.mant=d);a=this.exp+this.mant.length;if(0<a){if(a>b.digits&&0!=b.digits&&(this.form=b.form),a-1<=this.MaxExp)return this}else-5>a&&(this.form=b.form);a--;if(a<this.MinExp||a>this.MaxExp)b:{if(this.form==gx.num.dec.ENGINEERING&&(b=a%3,0>b&&(b=3+b),a-=b,a>=this.MinExp&&a<=this.MaxExp))break b;throw"finish(): Exponent Overflow: "+a;}return this}this.ind=
this.iszero;if(b.form!=gx.num.dec.PLAIN)this.exp=0;else if(0<this.exp)this.exp=0;else if(this.exp<this.MinExp)throw"finish(): Exponent Overflow: "+this.exp;this.mant=(new gx.num.dec.bigDecimal("0")).mant;return this};this.ispos=1;this.iszero=0;this.isneg=-1;this.MinExp=-999999999;this.MaxExp=999999999;this.MinArg=-999999999;this.MaxArg=999999999;this.plainMC=new gx.num.dec.mthctx(0,gx.num.dec.PLAIN);this.bytecar=Array(190);this.ind=0;this.form=gx.num.dec.PLAIN;this.mant=null;this.exp=0;if("undefined"!=
typeof m){"undefined"==typeof q&&(q=0);"undefined"==typeof v&&(v=m.length);"string"==typeof m&&(m=gx.text.trim(m),m=m.split(""));var C,w,n=0,p=0;var y=!1;var A=p=p=n=0,F=0;var x=0;0>=v&&this.bad("bigDecimal(): ",m);this.ind=this.ispos;"-"==m[0]?(v--,0==v&&this.bad("bigDecimal(): ",m),this.ind=this.isneg,q++):"+"==m[0]&&(v--,0==v&&this.bad("bigDecimal(): ",m),q++);y=C=!1;x=0;var G=w=-1;A=v;n=q;a:for(;0<A;A--,n++){p=m[n];if("0"<=p&&"9">=p){G=n;x++;continue a}if("."==p){0<=w&&this.bad("bigDecimal(): ",
m);w=n-q;continue a}if("e"!=p&&"E"!=p){("0">p||"9"<p)&&this.bad("bigDecimal(): ",m);C=!0;G=n;x++;continue a}n-q>v-2&&this.bad("bigDecimal(): ",m);y=!1;"-"==m[n+1]?(y=!0,n+=2):n="+"==m[n+1]?n+2:n+1;p=v-(n-q);(0==p||9<p)&&this.bad("bigDecimal(): ",m);v=p;p=n;for(;0<v;v--,p++)A=m[p],"0">A&&this.bad("bigDecimal(): ",m),"9"<A?this.bad("bigDecimal(): ",m):F=A-0,this.exp=10*this.exp+F;y&&(this.exp=-this.exp);y=!0;break a}0==x&&this.bad("bigDecimal(): ",m);0<=w&&(this.exp=this.exp+w-x);F=G-1;n=q;a:for(;n<=
F;n++)if(p=m[n],"0"==p)q++,w--,x--;else if("."==p)q++,w--;else break a;this.mant=Array(x);p=q;if(C)for(q=x,n=0;0<q;q--,n++)n==w&&p++,A=m[p],"9">=A?this.mant[n]=A-0:this.bad("bigDecimal(): ",m),p++;else for(q=x,n=0;0<q;q--,n++)n==w&&p++,this.mant[n]=m[p]-0,p++;0==this.mant[0]?(this.ind=this.iszero,0<this.exp&&(this.exp=0),y&&(this.mant=(new gx.num.dec.bigDecimal("0")).mant,this.exp=0)):y&&(this.form=gx.num.dec.SCIENTIFIC,x=this.exp+this.mant.length-1,(x<this.MinExp||x>this.MaxExp)&&this.bad("bigDecimal(): ",
m))}},mthctx:function(m,q,v,C){this.getDigits=function(){return this.digits};this.getForm=function(){return this.form};this.getLostDigits=function(){return this.lostDigits};this.getRoundingMode=function(){return this.roundingMode};this.toString=function(){var w=null;var n=this.form==gx.num.dec.SCIENTIFIC?"SCIENTIFIC":this.form==gx.num.dec.ENGINEERING?"ENGINEERING":"PLAIN";var p=gx.num.dec.ROUNDS.length;var y=0;a:for(;0<p;p--,y++)if(this.roundingMode==gx.num.dec.ROUNDS[y]){w=gx.num.dec.ROUNDWORDS[y];
break a}return"digits="+this.digits+" form="+n+" lostDigits="+(this.lostDigits?"1":"0")+" roundingMode="+w};this.isValidRound=function(w){var n=gx.num.dec.ROUNDS.length;var p=0;for(;0<n;n--,p++)if(w==gx.num.dec.ROUNDS[p])return!0;return!1};this.form=this.digits=0;this.lostDigits=!1;this.roundingMode=0;"undefined"==typeof C&&(C=gx.num.dec.DEFAULT_ROUNDINGMODE);"undefined"==typeof v&&(v=gx.num.dec.DEFAULT_LOSTDIGITS);"undefined"==typeof q&&(q=gx.num.dec.DEFAULT_FORM);if(m!=gx.num.dec.DEFAULT_DIGITS){if(m<
gx.num.dec.MIN_DIGITS)throw"mthctx(): Digits too small: "+m;if(m>gx.num.dec.MAX_DIGITS)throw"mthctx(): Digits too large: "+m;}if(q!=gx.num.dec.SCIENTIFIC&&q!=gx.num.dec.ENGINEERING&&q!=gx.num.dec.PLAIN)throw"mthctx() Bad form value: "+q;if(!this.isValidRound(C))throw"mthctx(): Bad roundingMode value: "+C;this.digits=m;this.form=q;this.lostDigits=v;this.roundingMode=C},PLAIN:0,SCIENTIFIC:1,ENGINEERING:2,ROUND_DOWN:1,ROUND_CEILING:2,ROUND_FLOOR:3,ROUND_HALF_DOWN:5,ROUND_HALF_EVEN:6,ROUND_HALF_UP:4,
ROUND_UNNECESSARY:7,ROUND_UP:0,DEFAULT_FORM:1,DEFAULT_DIGITS:9,DEFAULT_LOSTDIGITS:!1,DEFAULT_ROUNDINGMODE:4,MIN_DIGITS:0,MAX_DIGITS:999999999,ROUNDS:[4,7,2,1,3,5,6,0],ROUNDWORDS:"ROUND_HALF_UP ROUND_UNNECESSARY ROUND_CEILING ROUND_DOWN ROUND_FLOOR ROUND_HALF_DOWN ROUND_HALF_EVEN ROUND_UP".split(" ")};
